### ISSUE TITLE
I think rather than using Golang, you should use OOP scripting languages

### ISSUE THREAD

**Issue by LemonHX** [xpkhq/xpk#1]
Due to Golang only has only a simple `Interface & Implement` for abstraction is not suitable for writing complex logic.
If consider cross platform, I suggest using scripting language for abstraction( maybe ruby/python are good choices due to ruby has homebrew and python has bunch of linux packager written

**Comment by xtlsoft** [comment]
Actually this repository will contain infrastructure codes for an operating system. Considering Golang for fast implemention and this won't be discussed in a short period.
